//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCatalogWPF.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int IdCar { get; set; }
        public int IdBrand { get; set; }
        public int IdCountry { get; set; }
        public int Year { get; set; }
        public decimal Price { get; set; }
        public string ImageName { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Countries Countries { get; set; }
    }
}
